version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      
      # Server type configuration (CRITICAL FIX)
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc3/files/4889426
      
      # Memory configuration
      MEMORY: "6G"  # Sets both Xmx and Xms
      JVM_OPTS: >-
        -Xms4G
        -Xmx6G
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=32M
        -XX:+ParallelRefProcEnabled
        -Dlog4j2.formatMsgNoLookups=true
        -Dfml.ignoreInvalidMinecraftCertificates=true
        -Dfml.ignorePatchDiscrepancies=true

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"  # Add UDP for better connectivity

    volumes:
      - ./mc_data:/data
      # Fix mods directory mapping:
      - ./mods:/data/mods  # Correct path for Forge mods

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G  # Increased buffer for system processes