services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java8}
    volumes:
    - /root/minecraft/modpacks:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/bmc3-server.zip
      MEMORY: 6G
      ONLINE_MODE: "FALSE"           # Disable Mojang auth
      REMOVE_OLD_MODS: "true"        # Clean previous mods
      OVERRIDE_SERVER_PROPERTIES: "true"  # Use modpack's settings
      JVM_XX_OPTS: "-Xms4G -Xmx6G"
#      CF_SERVER_MOD: /modpacks/createlive3serverfiles+1.4.2.zip
#      CF_SERVER_MOD: /modpacks/Valhelsia+3-3.5.1-SERVER.zip
#      CF_SERVER_MOD: https://media.forgecdn.net/files/3012/800/SkyFactory-4_Server_4.2.2.zip
#      CF_SERVER_MOD: /modpacks/${MODPACK:-SkyFactory_4_Server_4.1.0.zip}
    ports:
      - "25565:25565"

volumes:
  data: {}