services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java8}
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/bmc3-server.zip
      #     CF_SERVER_MOD: /modpacks/createlive3serverfiles+1.4.2.zip
      #     CF_SERVER_MOD: /modpacks/Valhelsia+3-3.5.1-SERVER.zip
      #     CF_SERVER_MOD: https://media.forgecdn.net/files/3012/800/SkyFactory-4_Server_4.2.2.zip
      #     CF_SERVER_MOD: /modpacks/${MODPACK:-SkyFactory_4_Server_4.1.0.zip}
      ONLINE_MODE: "FALSE"           # Disable Mojang auth
      REMOVE_OLD_MODS: "true"        # Clean previous mods
      OVERRIDE_SERVER_PROPERTIES: "true"  # Use modpack's settings
      FORGE_INSTALLER: "forge-1.19.2-43.3.2-installer.jar"  # Critical fix
      
      # Memory configuration
      MEMORY: "6G"
      JVM_XX_OPTS: "-Xms4G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled"
      JVM_OPTS: "-Dlog4j2.formatMsgNoLookups=true"

      # Server settings
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - /root/minecraft/instances/bmc3/server-data:/data
      - /root/minecraft/modpacks:/modpacks
      - /root/minecraft/forge-installer:/forge  # Add Forge installer

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G