version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      
      # Correct CurseForge configuration
      TYPE: "CURSEFORGE"
      MODPACK: "550864:4889426"  # ProjectID:FileID (client version)
      VERSION: "1.19.2"  # Must match modpack's Minecraft version
      
      # Required for CurseForge API access
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc3/files/4889399"
      
      # Memory configuration
      MEMORY: "6G"
      JVM_XX_OPTS: "-Xms4G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled"
      JVM_OPTS: "-Dlog4j2.formatMsgNoLookups=true"

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - ./mc_data:/data

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G