version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"                   # Must accept Minecraft EULA
      TYPE: "FORGE"                  # Server type
      VERSION: "1.19.2"              # Minecraft version
      FORGE_VERSION: "43.3.2"        # Specific Forge version
      MODPACK: "/modpacks/bmc3-server.zip"  # Path to your modpack
      ONLINE_MODE: "FALSE"           # Disable Mojang auth
      REMOVE_OLD_MODS: "true"        # Clean previous mods
      OVERRIDE_SERVER_PROPERTIES: "true"  # Use modpack's settings
      
      # Memory configuration
      MEMORY: "6G"
      JVM_XX_OPTS: "-Xms4G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled"
      JVM_OPTS: "-Dlog4j2.formatMsgNoLookups=true"

      # Server settings
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - /root/minecraft/server-data:/data
      - /root/minecraft/modpacks:/modpacks  # Absolute path for root
      
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G