version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      
      # Correct server type configuration
      TYPE: "CURSEFORGE"  # Use TYPE instead of MODPACK_PLATFORM
      CF_API_KEY: ${CF_API_KEY}
      CF_SERVER_MOD: "550864:4889399"  # Use client modpack file ID here
      
      # Memory configuration
      MEMORY: "6G"
      JVM_OPTS: >-
        -Xms4G
        -Xmx6G
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=32M
        -XX:+ParallelRefProcEnabled
        -Dlog4j2.formatMsgNoLookups=true
        -Dfml.ignoreInvalidMinecraftCertificates=true
        -Dfml.ignorePatchDiscrepancies=true

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - ./mc_data:/data  # All mods/configs will be managed automatically

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G