version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      
      # Server type configuration (CRITICAL FIX)
      TYPE: "FORGE"  # Required for Better MC modpack
      VERSION: "1.20.1"  # Match Better MC 3 requirements
      FORGE_VERSION: "47.2.20"  # Specific version for 1.20.1

      # Memory configuration
      MEMORY: "6G"  # Sets both Xmx and Xms
      JVM_OPTS: >-
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=32M
        -XX:+ParallelRefProcEnabled
        -Dlog4j2.formatMsgNoLookups=true
        -Dfml.ignoreInvalidMinecraftCertificates=true
        -Dfml.ignorePatchDiscrepancies=true

      # Modrinth configuration
      MODRINTH_PROJECT_ID: "better-mc-forge-bmc3"
      MODRINTH_VERSION_ID: "v20"
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/citresewn-*.jar
        **/datapacks/BE_default_endgen_fix*
      MODRINTH_FORCE_SYNCHRONIZE: "true"

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"  # Add UDP for better connectivity

    volumes:
      - ./mc_data:/data
      # Fix mods directory mapping:
      - ./mods:/data/mods  # Correct path for Forge mods

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G  # Increased buffer for system processes