version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      
      # Server type configuration
      TYPE: "FORGE"  # Must use Forge for modded servers
      VERSION: "1.19.2"  # Match modpack's Minecraft version
      FORGE_VERSION: "43.3.2"  # From BMC3 server pack requirements
      
      # Direct server pack download
      MODPACK: "https://edge.forgecdn.net/files/4889/399/Better+MC+FORGE+Server+Pack+v20.zip"
      CF_API_KEY: ${CF_API_KEY}  # Still required for verification

      # Memory configuration
      MEMORY: "6G"
      JVM_XX_OPTS: "-Xms4G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled"
      JVM_OPTS: "-Dlog4j2.formatMsgNoLookups=true"

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_ROLLING_LOGS: "true"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"

    volumes:
      - ./mc_data:/data

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 7G