version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: better-mc-server
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      
      # Memory configuration (adjust based on your available RAM)
      MEMORY: 6G  # Sets -Xmx (max memory)
      JVM_OPTS: |
        -Xms4G  # Initial memory allocation
        -XX:+UseG1GC
        -XX:+UnlockExperimentalVMOptions
        -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=32M
        -XX:+AlwaysPreTouch
        -XX:+ParallelRefProcEnabled
        -XX:+DisableExplicitGC
        -XX:+PerfDisableSharedMem
        -Dlog4j2.formatMsgNoLookups=true
        -Dfml.ignoreInvalidMinecraftCertificates=true
        -Dfml.ignorePatchDiscrepancies=true

      # Modrinth configuration
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/better-mc-forge-bmc4/version/v32.5
      MODRINTH_PROJECT_ID: better-mc-forge-bmc4
      MODRINTH_VERSION_ID: v32.5
      MODRINTH_EXCLUDE_FILES: |
        XaeroPlus
        XaerosWorldMap
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/citresewn-*.jar
        **/datapacks/BE_default_endgen_fix*
      MODRINTH_FORCE_SYNCHRONIZE: "true"

      # Server settings
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "your-strong-password"

    ports:
      - "25565:25565"
      - "25575:25575"

    volumes:
      - ./mc_data:/data
      - ./mods:/mods

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 10G  # Should be ~2G more than Xmx
        reservations:
          memory: 6G